# Exploración Paquete Numpy

Orientado al análisis matemático y científico de datos :)

In [1]:
import numpy as np

## Declarando Arrays con Numpy

### Array 1D, 2D, 3D

In [18]:
# Declaración del primer array 1D

mi_primer_array_1D = np.array([7,8,6,4])
mi_primer_array_1D

array([7, 8, 6, 4])

In [20]:
mi_primer_array_1D.shape

(4,)

In [23]:
# Accediendo a los elementos de un array 1D

mi_primer_array_1D[1]

8

In [25]:
# Declaración del primer array 2D (Matriz)

mi_primer_array_2D = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
mi_primer_array_2D

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [26]:
# Accediendo a los elementos de un array 2D

# Forma 1
mi_primer_array[0][2]

8

In [27]:
# Forma 2
mi_primer_array[0,2]

8

In [28]:
# Declaración del primer array 3D

mi_primer_array_3D = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])
mi_primer_array_3D

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [30]:
mi_primer_array_3D.shape

(3, 2, 4)

In [31]:
# Accediendo a los elementos de un array 3D

#Forma 1
mi_primer_array_3D[1][0][1]

6

In [15]:
# Accediendo a los elementos de un array 3D

#Forma 2
mi_primer_array_3D[1,0,1]

6

### Creando arrays de ceros

In [42]:
# Array de 0s de 1D:

ceros_1D_arr = np.zeros(5)
ceros_1D_arr

array([0., 0., 0., 0., 0.])

In [45]:
# Array de 0s de 3D:
ceros_3D_arr = np.zeros((5,4,3))
ceros_3D_arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
# Array de 0s de 6D:
ceros_6D_arr = np.zeros((5,4,3,2,2,2))
ceros_6D_arr.shape

(5, 4, 3, 2, 2, 2)

### Creando arrays de unos

In [50]:
unos_2D_arr = np.ones((5,5))
unos_2D_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Operaciones con arrays DE LA MISMA dimensionalidad

In [51]:
mi_primer_array_2D

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [55]:
# Sumémosle 2 a cada elemento:
mi_primer_array_2D + np.ones((3,4))*2

array([[10.,  9., 10.,  7.],
       [ 4.,  8., 10.,  3.],
       [10., 10., 11.,  7.]])

In [56]:
# Intentemos operar con arrays de distinta dimensionalidad:
mi_primer_array_2D + np.ones((5,6))

ValueError: operands could not be broadcast together with shapes (3,4) (5,6) 

In [57]:
# Media de todos los valores del array:
mi_primer_array_2D.mean()

6.25

In [82]:
# Media de todos los valores de la primera fila del array:
mi_primer_array_2D[0].mean()

7.0

In [83]:
mi_primer_array_2D

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [84]:
# Calculame la media de dicha matriz por columnas (axis=0)
mi_primer_array_2D.mean(axis=0)

array([6.        , 7.        , 8.33333333, 3.66666667])

In [86]:
# Calculame la media de dicha matriz por filas (axis=1)
mi_primer_array_2D.mean(axis=1)

array([7.  , 4.25, 7.5 ])

### Reshape de arrays

In [89]:
array_2D_plano = mi_primer_array_2D.ravel()
array_2D_plano

array([8, 7, 8, 5, 2, 6, 8, 1, 8, 8, 9, 5])

In [95]:
array_2D_plano.reshape(2,6)

array([[8, 7, 8, 5, 2, 6],
       [8, 1, 8, 8, 9, 5]])

In [97]:
array_2D_plano.reshape(3,2,2)

array([[[8, 7],
        [8, 5]],

       [[2, 6],
        [8, 1]],

       [[8, 8],
        [9, 5]]])

### np.random

In [100]:
# Generar un array 2D (una matriz) de 3 filas y 3 columnas con números aleatorios entre 0 y 1:

np.random.rand(3,3)

array([[0.07993044, 0.17945812, 0.19258735],
       [0.95766693, 0.14314885, 0.29819953],
       [0.052536  , 0.58117931, 0.36919274]])